[[project]]
name = "Matching Engine"
desc = "A matching engine implementation in Rust"
links = [
	{name = "GitHub", url = "https://github.com/ffucci/matching_engine_rs"}
]

[[project]]
name = "Montecarlo Options"
desc = "A small C++20 framework to perform Montecarlo pricing"
links = [
	{name = "GitHub", url = "https://github.com/ffucci/montecarlo_options"},
]

[[project]]
name = "UModules"
desc = "A sequencer in VCV Rack written in C++"
links = [
	{name = "", url = ""},
]