[[project]]
name = "Montecarlo Options"
desc = "A small C++20 framework to perform Montecarlo pricing"
links = [
	{name = "", url = ""},
	{name = "", url = ""}
]

[[project]]
name = "UModules"
desc = "A sequencer in VCV Rack written in C++"
links = [
	{name = "", url = ""},
	{name = "", url = ""}
]